services:
  mysql:
    image: mysql:8.2.0
    container_name: horizon-dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: horizon
    ports:
      - "3306:3306"
    networks:
      - dev

  redis:
    image: redis:7.0.14
    container_name: horizon-dev-redis
    environment:
      - REDIS_PASSWORD=1234
    command: ["redis-server", "--requirepass", "1234"]
    ports:
      - "36379:6379"
    networks:
      - dev

networks:
  dev:
    name: horizon-development-network
