services:
  mysql:
    image: mysql:8.2.0
    container_name: horizon-dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: horizon
    ports:
      - "3306:3306"
    networks:
      - dev

  redis:
    image: redis:7.0.14
    container_name: horizon-dev-redis
    environment:
      - REDIS_PASSWORD=1234
    command: [ "redis-server", "--requirepass", "1234" ]
    ports:
      - "36379:6379"
    networks:
      - dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - dev

  kibana:
    container_name: horizon-log-service-kibana
    image: kibana:7.17.21
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -I http://localhost:5601 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - elasticsearch
    networks:
      - dev

networks:
  dev:
    name: horizon-development-network
