services:
  mysql:
    image: mysql:8.2.0
    container_name: horizon-dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: horizon
    ports:
      - "3306:3306"
    networks:
      - horizon-dev-network

  redis:
    image: redis:7.0.14
    container_name: horizon-dev-redis
    environment:
      - REDIS_PASSWORD=1234
    command: [ "redis-server", "--requirepass", "1234" ]
    ports:
      - "36379:6379"
    networks:
      - horizon-dev-network

  # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - horizon-dev-network
  kibana:
    container_name: horizon-log-service-kibana
    image: kibana:7.17.21
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -I http://localhost:5601 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - elasticsearch
    networks:
      - horizon-dev-network

  # Kafka
  zookeeper:
    container_name: horizon-zookeeper
    image: bitnami/zookeeper:3.8.4
    ports:
      - '22181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - horizon-dev-network
  kafka:
    image: bitnami/kafka:3.6
    user: root
    ports:
      - '29092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=horizon-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - horizon-dev-network
    depends_on:
      - zookeeper

networks:
  horizon-dev-network:
    name: horizon-development-network
