services:
  redis:
    container_name: horizon-redis
    image: redis:7.0.14
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    extends:
      file: common.yml
      service: horizon-base-config

  account-db:
    container_name: horizon-account-db
    image: mysql:8.2.0
    volumes:
      - ./horizon-account-db-data:/var/lib/mysql
      - ./horizon-account-db-conf:/etc/mysql
    environment:
      MYSQL_DATABASE: horizon
    extends:
      file: common.yml
      service: horizon-db-config

  transaction-db:
    container_name: horizon-transaction-db
    image: mysql:8.2.0
    volumes:
      - ./horizon-transaction-db-data:/var/lib/mysql
      - ./horizon-transaction-db-conf:/etc/mysql
    environment:
      MYSQL_DATABASE: horizon
    extends:
      file: common.yml
      service: horizon-db-config

  bank-db:
    container_name: horizon-bank-db
    image: mysql:8.2.0
    volumes:
      - ./horizon-bank-db-data:/var/lib/mysql
      - ./horizon-bank-db-conf:/etc/mysql
    environment:
      MYSQL_DATABASE: horizon
    extends:
      file: common.yml
      service: horizon-db-config

  user-db:
    container_name: horizon-user-db
    image: mysql:8.2.0
    volumes:
      - ./horizon-user-db-data:/var/lib/mysql
      - ./horizon-user-db-conf:/etc/mysql
    environment:
      MYSQL_DATABASE: horizon
      SPRING_DATA_REDIS_PASSWORD: "${REDIS_PASSWORD}"
    extends:
      file: common.yml
      service: horizon-db-config

  dwolla-db:
    container_name: horizon-dwolla-db
    image: mysql:8.2.0
    volumes:
      - ./horizon-dwolla-db-data:/var/lib/mysql
      - ./horizon-dwolla-db-conf:/etc/mysql
    environment:
      MYSQL_DATABASE: horizon
    extends:
      file: common.yml
      service: horizon-db-config

  plaid-db:
    container_name: horizon-plaid-db
    image: mysql:8.2.0
    volumes:
      - ./horizon-plaid-db-data:/var/lib/mysql
      - ./horizon-plaid-db-conf:/etc/mysql
    environment:
      MYSQL_DATABASE: horizon
    extends:
      file: common.yml
      service: horizon-db-config

  configserver:
    container_name: horizon-config-server
    image: leopoldhsing2/horizon.config-server
    environment:
      SPRING_PROFILES_ACTIVE: native
    extends:
      file: common.yml
      service: horizon-microservice-config

  eureka-server:
    container_name: horizon-eureka-server
    image: leopoldhsing2/horizon.eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

  gateway:
    container_name: horizon-gateway
    image: leopoldhsing2/horizon.gateway
    environment:
      SPRING_APPLICATION_NAME: "gateway"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_DATA_REDIS_PASSWORD: "${REDIS_PASSWORD}"
      HORIZON_URL_PATTERN_LOGIN_PATH: "https://horizon.discobroccoli.com/sign-in"
    depends_on:
      eureka-server:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

  account:
    container_name: horizon-account
    image: leopoldhsing2/horizon.account
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_APPLICATION_NAME: "account"
      SPRING_DATASOURCE_URL: "jdbc:mysql://horizon-account-db:3306/horizon"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      account-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

  transaction:
    container_name: horizon-transaction
    image: leopoldhsing2/horizon.transaction
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_APPLICATION_NAME: "transaction"
      SPRING_DATASOURCE_URL: "jdbc:mysql://horizon-transaction-db:3306/horizon"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      transaction-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

  bank:
    container_name: horizon-bank
    image: leopoldhsing2/horizon.bank
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_APPLICATION_NAME: "bank"
      SPRING_DATASOURCE_URL: "jdbc:mysql://horizon-bank-db:3306/horizon"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      bank-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

  user:
    container_name: horizon-user
    image: leopoldhsing2/horizon.user
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_APPLICATION_NAME: "user"
      SPRING_DATASOURCE_URL: "jdbc:mysql://horizon-user-db:3306/horizon"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      SPRING_DATA_REDIS_PASSWORD: "${REDIS_PASSWORD}"
    depends_on:
      user-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

  dwolla:
    container_name: horizon-dwolla
    image: leopoldhsing2/horizon.dwolla
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_APPLICATION_NAME: "dwolla"
      SPRING_DATASOURCE_URL: "jdbc:mysql://horizon-dwolla-db:3306/horizon"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      DWOLLA_BASE_URL: "${DWOLLA_BASE_URL}"
      DWOLLA_KEY: "${DWOLLA_KEY}"
      DWOLLA_SECRET: "${DWOLLA_SECRET}"
      DWOLLA_ENV: "${DWOLLA_ENV}"
    depends_on:
      dwolla-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

  plaid:
    container_name: horizon-plaid
    image: leopoldhsing2/horizon.plaid
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://horizon-config-server:8080/
      SPRING_APPLICATION_NAME: "plaid"
      SPRING_DATASOURCE_URL: "jdbc:mysql://horizon-plaid-db:3306/horizon"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      SPRING_DATA_REDIS_PASSWORD: "${REDIS_PASSWORD}"
      PLAID_CLIENT_ID: "${PLAID_CLIENT_ID}"
      PLAID_SECRET: "${PLAID_SECRET}"
      PLAID_ENV: "${PLAID_ENV}"
    depends_on:
      plaid-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    extends:
      file: common.yml
      service: horizon-microservice-config

networks:
  horizon-default-network:
    driver: "bridge"
    name: "horizon-default-network"
