services:
  mysql:
    image: mysql:8.3.0
    container_name: horizon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: horizon
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    name: horizon-default-network
