server:
  port: 9005

spring:
  application:
    name: gateway
  data:
    redis:
      host: localhost
      port: 36379
      password: 1234
      database: 0
  config:
    import: "configserver:http://localhost:9000/"

horizon:
  url:
    pattern:
      inner-uri-patterns: /api/**/inner/**
      trusted-uri-patterns:
        - /css/**
        - /js/**
        - /ts/**
        - /img/**
        - /fonts/**
      login-path: http://localhost:3000/sign-in
      require-auth-uri-patterns:
        - /api/**
      sign-in-uri-patterns: /api/*/user/sign-in
      sign-up-uri-patterns: /api/*/user/sign-up
