spring:
  application:
    name: plaid
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:9000/"
server:
  port: 9006

plaid:
  client-id: 6650078958d6ed001ce3678b
  secret: 36357754a0b0f02828a2247007735e
  env: sandbox
  products:
    - auth
    - transactions
    - identity
  country-codes:
    - US
    - CA
