spring:
  application:
    name: plaid
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:9000/"
server:
  port: 9006

plaid:
  client-id:
  secret:
  env: sandbox
  products:
    - auth
    - transactions
    - identity
  country-codes:
    - US
    - CA
