spring:
  application:
    name: user
  profiles:
    active: test
  config:
    import: "configserver:http://horizon-config-server:8080/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "user"
    description: "Horizon user microservice application"
    version: "0.0.1"

