spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
#        git:
#          uri: https://...git
#          default-label: "main"
#          timeout: 5            # timout in 5s
#          clone-on-start: true  # clone repository to local when start
#          force-pull: true      # overwrite local changes when start/restart

server:
  port: 9000

horizon:
  plaid:
    client-id: 662e1e5fdca064001c3e0086
    secret: be405988983be57fe34bef8e9038b3
    env: sandbox
    products:
      - auth
      - transactions
      - identity
    country-codes:
      - US
      - CA
  dwolla:
    base-url: https://api-sandbox.dwolla.com
    key: qAN5xkFYOSQeUNpN7GSPcGPHH8nSpVrPKSL8Ye5mSSP5AzddNt
    secret: FI50i6NbUQ90106Bt1n9bH6aCNWhcs8Rliy7VRqrXgNbKtLy00
    env: sandbox
