spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/horizon
    username: root
    password: 1234
  jpa:
    show-sql: true

dwolla:
  base-url: https://api-sandbox.dwolla.com
  key: qAN5xkFYOSQeUNpN7GSPcGPHH8nSpVrPKSL8Ye5mSSP5AzddNt
  secret: FI50i6NbUQ90106Bt1n9bH6aCNWhcs8Rliy7VRqrXgNbKtLy00
  env: sandbox
