server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dwolla-db:3306/horizon
    username: root
    password: 1234
  jpa:
    show-sql: true

dwolla:
  base-url: https://api-sandbox.dwolla.com
  key: 4XeCnXt8G1z2ak8iGLM1aAhNtAI3axX2djSSDoGrAHHrvhfbEf
  secret: 1wKHN3dL9grT45hlkeyr5d0AkRYLkkgkuZicpe5HqOe66M5oKS
  env: sandbox

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "dwolla"
    description: "Horizon dwolla microservice application"
    version: "0.0.1"
