server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://horizon-plaid-db:3306/horizon
    username: root
    password: 1234
  data:
    redis:
      host: horizon-redis
      port: 6379
      password: 1234
      database: 1
  jpa:
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://horizon-eureka-server:8080/eureka/

plaid:
  products:
    - auth
    - transactions
    - identity
  country-codes:
    - US
    - CA

