server:
  port: 9008

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/horizon
    username: root
    password: 1234
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 36379
      password: 1234
      database: 2

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/

info:
  app:
    name: "transaction"
    description: "Horizon transaction microservice application"
    version: "0.0.1"
